name:                ltl-translators
version:             0.1.0.0
github:              "p4l1ly/ltl-translators"
license:             BSD3
author:              "Pavol Vargovčík"
maintainer:          "pavol.vargovcik@gmail.com"
copyright:           "2019 Pavol Vargovčík"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/p4l1ly/ltl-translators#readme>

dependencies:
- base >= 4.7 && < 5
- interpolatedstring-perl6
- parsec
- mtl
- containers
- ghc


library:
  source-dirs: src

executables:
  ltl-translators-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ltl-translators

  ltl-generator-exe:
    main:                Main.hs
    source-dirs:         generator
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ltl-translators
    - safe

  ltl-randgen-exe:
    main:                Main.hs
    source-dirs:         randgen
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ltl-translators
    - random

tests:
  ltl-translators-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ltl-translators
